version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    restart: always
    environment:
      - APP_NAME=EpiSim
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "${DEV_PORT}:80"
      # - "${PORT}:80"  # production