version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    restart: always
    environment:
      - APP_NAME=EpidemicModels
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "4401:80"
      # - "80:80"  # production