version: "3.7"

services:

  app:
    build: ./app
    container_name: app
    restart: always
    env_file:
      - .env
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "${DEV_PORT}:80"
      # - "${PORT}:80"  # production