name: app build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker-build:
  
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [ prod, dev ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start containers
      run: make build ENV={{matrix.environment}}

    - name: Stop containers
      if: always()
      run: make down ENV={{matrix.environment}}
